---
- name: Get info on Docker Swarm
  delegate_to: "{{ groups['masters'][0] }}"
  run_once: true
  docker_swarm_info:
  register: swarm_info

- name: Join as slave
  docker_swarm:
    state: join
    advertise_addr: "{{ ansible_default_ipv4['address'] }}"
    join_token: "{{ swarm_info.swarm_facts.JoinTokens.Worker }}"
    remote_addrs: [ "{{ hostvars[groups['masters'][0]].ansible_facts.default_ipv4.address }}" ]

