---
- name: Recherche des devices
  register: devs
  find:
    paths: /dev
    file_type: 'any'
    patterns: 'dm-*'

- name: Create a directory if it does not exist
  file:
    path: "{{ item.path }}"
    state: directory
  with_items:
    - { path: "/etc/systemd/nspawn/", desc: "nspawn base directory" }
    - { path: "/etc/systemd/system/systemd-nspawn@{{ container_name }}.service.d/", desc: "Client custom directory" }
  loop_control:
    label: "{{ item.desc }}"

- name: Generate the container_name nspawn configuration
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - { src: 'override.conf.j2',    dest: "/etc/systemd/system/systemd-nspawn@{{ container_name }}.service.d/override.conf", desc: 'Client startup overrides' }
    - { src: 'client.nspawn.j2', dest: '/etc/systemd/nspawn/{{ container_name }}.nspawn',      desc: 'nspawn configuration for this client' }
  loop_control:
    label: "{{ item.desc }}"

- name: Configuration des modules à charger
  lineinfile:
    path: "/etc/modules"
    regexp: '{{ item }}'
    line: '{{ item }}'
  with_items:
    - dm_mod
    - bridge
    - br_netfilter
    - fuse
    - ceph

- name: Load the requiered modules
  modprobe:
    name: '{{ item }}'
    state: present
  with_items:
    - dm_mod
    - bridge
    - br_netfilter
    - fuse
    - ceph

#- name: Configuration de l'IP forward
#  lineinfile:
#    path: "/etc/sysctl.conf"
#    regexp: 'net.ipv4.ip_forward'
#    line: 'net.ipv4.ip_forward=1'

- name: Activation de l'ip forward
  sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    sysctl_set: yes
    reload: yes
