---
- name: start the container
  systemd:
    daemon_reload: yes
    state: started
    enabled: yes
    masked: no
    name: systemd-nspawn@{{ container_name }}

- name: Attendre que le container soit pret
  wait_for:
    port: 2222
    timeout: 300
    delay: 1

