---
- name: Configuration du fichier /etc/hosts
  template:
    src: hosts.j2
    dest: /etc/hosts

- name: Création des répertoires ceph manquant
  file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  with_items:
    - "/var/lib/ceph/bootstrap-osd"
    - "/etc/ceph"

- name: Récuperer la configuration ceph
  delegate_to: "{{ groups['mons'][0] }}"
  run_once: true
  slurp:
    src: "{{ item }}"
  register: conf_ceph
  with_items:
    - "/etc/ceph/ceph.client.admin.keyring"
    - "/etc/ceph/ceph.conf"
    - "/var/lib/ceph/bootstrap-osd/ceph.keyring"

- name: Copier la configuration ceph
  copy:
    dest: "{{ item.item }}"
    content: "{{ item.content|b64decode }}"
  when: inventory_hostname != groups['mons'][0]
  with_items:
    - "{{ conf_ceph.results }}"
  loop_control:
    label: "{{ item.source }}"

- name: Gestion des permissions sur la clé
  file:
    path: "{{ item.path }}"
    owner: ceph
    group: ceph
    mode: "{{ item.mode }}"
  with_items:
    - { path: "/etc/ceph/ceph.client.admin.keyring", mode: '0600' }
    - { path: "/etc/ceph/ceph.conf", mode: '0644' }
    - { path: "/var/lib/ceph/bootstrap-osd/ceph.keyring", mode: '0600' }
  loop_control:
    label: "{{ item.path }}"
